const path = require('path');
const Asset = require('./Asset');
const AssetInline = require('./AssetInline');
const AssetScript = require('./AssetScript');
const { resolveException, duplicateScriptWarning, duplicateStyleWarning } = require('./Exceptions');

/**
 * @singleton
 */
class Resolver {
  fs = null;

  /**
   * @type {string} The issuer filename of required the file.
   */
  issuer = '';

  /**
   * @type {string} The context directory of required the file.
   */
  context = '';

  /**
   * The cache of resolved source files. Defined at one time.
   *
   * @type {Map<string, Map<string, string>>}
   */
  sourceFiles = new Map();

  /**
   * The data of assets sources and issuers. Used for resolving output assets.
   * For each new chunk must be cleaned.
   * Note: same module can have many issuers and can be saved under different asset filenames.
   *
   * @type {Map<string, {issuers:Map, originalAssetFile:string, moduleHandler?:Function<originalAssetFile:string, issuer:string>}>}
   */
  data = new Map();

  /**
   * The cache of duplicate scripts and styles.
   */
  duplicates = new Map();

  constructor() {
    // bind this context to the method for using in VM context
    this.require = this.require.bind(this);
  }

  /**
   *
   * @param {FileSystem} fs
   * @param {string} rootContext The Webpack root context path.
   */
  init({ fs, rootContext }) {
    this.fs = fs;
    this.rootContext = rootContext;
  }

  /**
   * Clear caches.
   * This method is called only once, when the plugin is applied.
   */
  clear() {
    this.data.clear();
    this.sourceFiles.clear();
  }

  /**
   * Reset settings.
   * This method is called before each compilation after changes by `webpack serv/watch`.
   */
  reset() {
    this.data.forEach((item) => item.issuers.clear());
    this.duplicates.clear();
  }

  /**
   * Set the current source file, which is the issuer for assets when compiling the source code.
   *
   * @param {string} issuer
   */
  setIssuer(issuer) {
    this.issuer = issuer;
    this.context = path.dirname(issuer);
  }

  /**
   * Add the context and resolved path of the resource to resolve it in require() at render time.
   *
   * @param {string} sourceFile The full path of source asset file.
   * @param {string} assetFile The original asset filename generated by Webpack, relative by output path.
   * @param {string} issuer The issuer of asset file.
   */
  addAsset(sourceFile, assetFile, issuer) {
    sourceFile = path.resolve(sourceFile);

    let item = this.data.get(sourceFile);
    if (!item) {
      this.data.set(sourceFile, {
        issuers: new Map([[issuer, undefined]]),
        originalAssetFile: assetFile,
      });
      return;
    }

    // don't override already resolved assets
    if (!item.issuers.has(issuer)) {
      item.issuers.set(issuer, undefined);
    }
    if (assetFile != null) item.originalAssetFile = assetFile;
  }

  /**
   * Add the resolved output asset file.
   *
   * @param {string} sourceFile The full path of source asset file.
   * @param {string} assetFile The resolved output asset filename, given the auto public path.
   * @param {string} issuer The issuer of asset file.
   */
  addResolvedAsset(sourceFile, assetFile, issuer) {
    sourceFile = path.resolve(sourceFile);

    let item = this.data.get(sourceFile);
    if (!item) {
      this.data.set(sourceFile, {
        issuers: new Map([[issuer, assetFile]]),
      });
      return;
    }
    item.issuers.set(issuer, assetFile);
  }

  /**
   * @param {string} sourceFile The full path of source asset file.
   * @param {Object} moduleHandler External handler for processing of the asset module.
   */
  setModuleHandler(sourceFile, moduleHandler = null) {
    let item = this.data.get(sourceFile);
    if (item) {
      item.moduleHandler = moduleHandler;
    }
  }

  /**
   * Resolve full path of asset source file by raw request and issuer.
   *
   * @param {string} rawRequest The raw request of resource.
   * @param {string} issuer The issuer of resource.
   * @return {string|null} The resolved full path of resource.
   */
  getSourceFile(rawRequest, issuer) {
    let sourceFile = this.sourceFiles.get(issuer)?.get(rawRequest);
    if (sourceFile) return sourceFile;

    // normalize request, e.g. the relative `path/to/../to/file` path to absolute `path/to/file`
    sourceFile = path.resolve(this.context, rawRequest);
    const [file] = sourceFile.split('?', 1);

    if (rawRequest.startsWith(this.context) || this.fs.existsSync(file)) {
      this.addSourceFile(sourceFile, rawRequest, issuer);
      return sourceFile;
    }

    return null;
  }

  /**
   * Add resolved source file to data.
   *
   * @param {string} sourceFile The resolved full path of resource.
   * @param {string} rawRequest The rawRequest of resource.
   * @param {string} issuer The issuer of resource.
   */
  addSourceFile(sourceFile, rawRequest, issuer) {
    let item = this.sourceFiles.get(issuer);
    if (item == null) {
      this.sourceFiles.set(issuer, new Map([[rawRequest, sourceFile]]));
    } else {
      item.set(rawRequest, sourceFile);
    }
  }

  /**
   * Whether in issuer used duplicate script or style.
   * Note: using duplicate scripts in the same Pug file doesn't make sense, must be used only one file.
   *
   * @param {string} file
   * @param {string} issuer
   * @return {boolean}
   */
  isDuplicate(file, issuer) {
    if (!this.duplicates.has(issuer)) {
      this.duplicates.set(issuer, new Set([file]));
      return false;
    }

    const duplicate = this.duplicates.get(issuer);
    if (duplicate.has(file)) return true;

    duplicate.add(file);
    return false;
  }

  /**
   * Resolve output asset filename, given the auto public path.
   *
   * @param {string} sourceFile The resolved full path of resource.
   * @param {string} issuer The issuer of resource.
   * @return {string|null}
   */
  resolveAsset(sourceFile, issuer) {
    const item = this.data.get(sourceFile);
    if (!item) return null;

    let assetFile = item.issuers.get(issuer);
    if (assetFile) return assetFile;

    const { originalAssetFile, moduleHandler } = item;

    let assetOutputFile;
    if (originalAssetFile != null) {
      // normalize output asset files
      if (AssetInline.isDataUrl(originalAssetFile)) {
        assetOutputFile = originalAssetFile;
      } else {
        const issuerAssetFile = Asset.findAssetFile(issuer);
        if (issuerAssetFile) {
          assetOutputFile = Asset.getOutputFile(originalAssetFile, issuerAssetFile);
        }
      }
    } else if (moduleHandler != null) {
      // normalize output asset files processed via external loader, e.g. `responsive-loader`
      assetOutputFile = moduleHandler(originalAssetFile, issuer);
    }

    if (assetOutputFile != null) {
      item.issuers.set(issuer, assetOutputFile);
    }

    return assetOutputFile;
  }

  /**
   * Require the resource request in the compiled pug or css.
   *
   * @param {string} rawRequest The raw request of source resource.
   * @returns {string} The output asset filename generated by filename template.
   * @throws {Error}
   */
  require(rawRequest) {
    const { issuer, context } = this;
    const request = path.resolve(context, rawRequest);

    // @import CSS rule is not supported
    if (rawRequest.indexOf('??ruleSet') > 0) resolveException(rawRequest, issuer);

    // require script in tag <script src=require('./main.js')>, asset filename set via replaceSourceFilesInCompilation()
    const scriptFile = AssetScript.resolveFile(rawRequest);

    if (scriptFile != null) {
      if (this.isDuplicate(scriptFile, issuer)) {
        const filePath = path.relative(this.rootContext, scriptFile);
        const issuerPath = path.relative(this.rootContext, issuer);
        duplicateScriptWarning(filePath, issuerPath);
      }

      return scriptFile;
    }

    // bypass the asset contained data-URL
    if (AssetInline.isDataUrl(rawRequest)) return rawRequest;

    // bypass the asset/inline as inline SVG
    if (AssetInline.isInlineSvg(request, issuer)) return request;

    // resolve resources
    const sourceFile = this.getSourceFile(rawRequest, issuer);
    if (sourceFile != null) {
      const assetFile = this.resolveAsset(sourceFile, issuer);
      if (assetFile != null) {
        if (assetFile.endsWith('.css') && this.isDuplicate(assetFile, issuer)) {
          const filePath = path.relative(this.rootContext, sourceFile);
          const issuerPath = path.relative(this.rootContext, issuer);
          duplicateStyleWarning(filePath, issuerPath);
        }
        return assetFile;
      }
      // try to resolve inline data url
      const dataUrl = AssetInline.getDataUrl(sourceFile, issuer);
      if (dataUrl != null) return dataUrl;
    }

    // require only js code or json data
    if (/\.js[a-z0-9]*$/i.test(rawRequest)) return require(request);

    resolveException(rawRequest, issuer);
  }
}

module.exports = new Resolver();
