const path = require('path');
const plugin = 'pug-plugin';

const isFunction = (value) => typeof value === 'function';

/**
 * Require the resource file from source in pug template.
 *
 * @param {string} file The required file from source directory.
 * @returns {string} The output asset filename generated by filename template.
 */
const requireResource = (file) => {
  const self = requireResource;
  // normalize the path, e.g.: 'path/to/../to/file' => 'path/to/file'
  const normalizedFile = path.join(file);
  const assetFile = self.resources[normalizedFile];

  return path.join(self.publicPath, assetFile);
};

/**
 * @type {string} The the output public path is `webpack.options.output.publicPath`.
 */
requireResource.publicPath = '';

/**
 * The mapping of the source file to the generated asset file.
 * @type {{key: string}}
 */
requireResource.resources = {};

/**
 * Simple equal of two objects.
 *
 * @param {{}} obj1
 * @param {{}} obj2
 * @return {boolean}
 */
const shallowEqual = function (obj1, obj2) {
  const keys1 = Object.keys(obj1);
  const keys2 = Object.keys(obj2);

  if (keys1.length !== keys2.length) return false;

  for (let key of keys1) {
    if (obj1[key] !== obj2[key]) return false;
  }

  return true;
};

module.exports = {
  plugin,
  isFunction,
  requireResource,
  shallowEqual,
};
